# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da22513a7b91a2a897f9363297aff810af88d40541d8c9259d5fbb64dcac135eb64fc65a6f6a206da719496b78de5dfa53b1600285ff140fab5633d2a82a1fa1

test:
  secret_key_base: e86f098dda186eab80c715b5c89849c83642d263a3f6d323682a26767b8a636b1a006164c423c97b54ef46533119b0031c888c51e6354988159078fecd29b139

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
